version: "3.8"
services:
  pg_database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cuddly_dollop_dev
    volumes:
      - /tmp/docker/pg_database:/tmp/pg_database
