name: DSOMM Security Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # 1. SAST (Static Application Security Testing)
  sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  # 2. SCA (Software Composition Analysis) + SBOM
  dependency-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  # 3. Secrets Detection
  secrets-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Scan for secrets with Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml  # Конфиг для исключений

  # 4. DAST (Dynamic Application Security Testing)
  dast:
    needs: [sast, dependency-scan, secrets-check]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  # 5. Container Security (если используется Docker)
  container-scan:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'  # Только при пушах в main
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  # 6. Deploy (только если все проверки пройдены)
  deploy:
    needs: [sast, dependency-scan, secrets-check, dast, container-scan]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        run: echo "Deploying securely to production..."